import numpy as np
a=np.array([10,20,30,40])
b=np.array([5,4,6,8])
print(a*b)
print(a-b)
print(a+b)
print(a/b)
print(a*2)
print(b**2)
print(np.sum(a))
print(np.mean(a))
print(np.std(a))
print(np.max(a))
print(np.min(a))